name: dart_frog_dev_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog_gen:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog_gen
      ref: a601d4fb20eb271569c56ff4f79e832d17b8bd5c
  mason: ">=0.1.0-dev <0.1.0"
