name: dart_frog_dev_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog_gen:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog_gen
      ref: b4425bf8abf1f5d4be05bb8448e03ec593c2fc95
  mason: ">=0.1.0-dev <0.1.0"
