name: dart_frog_prod_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog_gen:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog_gen
      ref: 2687edb5d80ca5077c54e42941d8c36e464bf888
  mason: ">=0.1.0-dev <0.1.0"
  path: ^1.8.1
