name: dart_frog_prod_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog_gen:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog_gen
      ref: 457e1a4959320b3cc98769f4c165d1f4977fccac
  mason: ">=0.1.0-dev <0.1.0"
  path: ^1.8.1
  pubspec_parse: ^1.2.0
