name: dart_frog_test
description: A testing library for Dart Frog
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  shelf: ^1.1.0
  shelf_hotreload: ^1.1.0
  shelf_router: ^1.0.0
  test: ^1.19.2

dev_dependencies:
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
